# Generated by Django 5.0.6 on 2024-06-21 11:57

import django.db.models.deletion
import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeasureUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_cs", models.TextField()),
                ("description_en", models.TextField()),
                ("description_de", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("code", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=stock.models.image_file_path
                    ),
                ),
                (
                    "measure_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.measureunit",
                    ),
                ),
            ],
        ),
    ]
