# Generated by Django 5.0.6 on 2024-06-23 14:49

import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_product_description_cs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=stock.models.image_file_path
            ),
        ),
    ]
