# Generated by Django 5.0.6 on 2024-06-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
