# Generated by Django 5.0.6 on 2024-06-24 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="tag",
            field=models.ManyToManyField(
                related_name="tag_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
