# Generated by Django 5.0.6 on 2024-06-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        choices=[
                            ("MRS", "Mrs."),
                            ("MR", "Mr."),
                            ("MS", "Ms."),
                            ("DOCTOR", "Doctor(ka)"),
                            ("PAN", "Pan"),
                            ("PANI", "Paní"),
                        ],
                        max_length=100,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("delivery_address", models.CharField(max_length=255)),
                ("invoice_address", models.CharField(max_length=255)),
                ("tax_number", models.CharField(max_length=255)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.contact"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PRODUCTION", "In Production"),
                            ("READY_TO_GO", "Ready to Go"),
                            ("ON_HOLD", "On Hold"),
                            ("INVOICING", "Invoicing"),
                            ("FINISHED", "Finished"),
                            ("COMPLAINED", "Complained"),
                            ("RENTED", "Rented"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "production_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("BACKLOG", "Backlog"),
                            ("ON_HOLD", "On Hold"),
                            ("TO_DO", "To Do"),
                            ("HW", "HW"),
                            ("FV_SW", "FV/SW"),
                            ("TESTING", "Testing"),
                            ("READY", "Ready"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField()),
                ("internal_deadline", models.DateField()),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "on_hold_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INFORMATION", "Information"),
                            ("COMPONENT", "Component"),
                            ("GLASS", "Glass"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.customer"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.company"
                    ),
                ),
            ],
        ),
    ]
