# Generated by Django 5.0.6 on 2024-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="salutation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MRS", "Mrs."),
                    ("MR", "Mr."),
                    ("MS", "Ms."),
                    ("DOCTOR", "Doctor(ka)"),
                    ("PAN", "Pan"),
                    ("PANI", "Paní"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
