# Generated by Django 5.0.6 on 2024-06-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_company_email_alter_company_tax_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.company",
            ),
        ),
    ]
