# Generated by Django 5.0.6 on 2024-06-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_order_customer_alter_order_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.customer",
            ),
        ),
    ]
