# Generated by Django 5.0.6 on 2024-06-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_company_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="end_user",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
