# Generated by Django 5.0.6 on 2024-06-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_order_end_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="direct_customer",
        ),
    ]
